// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNmmnLeqTHrAw33tOAAImjhVgn3Rh8DM0',
    appId: '1:897015960885:web:78ee7e12c04d0f3ad8e87c',
    messagingSenderId: '897015960885',
    projectId: 'signup-ff4c2',
    authDomain: 'signup-ff4c2.firebaseapp.com',
    storageBucket: 'signup-ff4c2.appspot.com',
    measurementId: 'G-57KQF6LND8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRBWB50atG-7l3fD8Hm0AeDWqhSBjyFGY',
    appId: '1:897015960885:android:edbfde35d3ce5489d8e87c',
    messagingSenderId: '897015960885',
    projectId: 'signup-ff4c2',
    storageBucket: 'signup-ff4c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9P7mRlWurR0x7OXr8dJHcw6DLhq-nY6c',
    appId: '1:897015960885:ios:8bd734c8654c5ad9d8e87c',
    messagingSenderId: '897015960885',
    projectId: 'signup-ff4c2',
    storageBucket: 'signup-ff4c2.appspot.com',
    iosClientId: '897015960885-ucjvqfce77rh7ug3rj7rucvljm1slmnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupgoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9P7mRlWurR0x7OXr8dJHcw6DLhq-nY6c',
    appId: '1:897015960885:ios:6e722375a872846dd8e87c',
    messagingSenderId: '897015960885',
    projectId: 'signup-ff4c2',
    storageBucket: 'signup-ff4c2.appspot.com',
    iosClientId: '897015960885-h3k2hjdr4fb7hn1oroe2tv2ds6dkr3sf.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupgoogle.RunnerTests',
  );
}
